### ISSUE TITLE
Testing with t.equals

### ISSUE THREAD

**Issue by sohilpandya** [NodeGroup2/GRAGS#26]
I would love to know what the reasons are behind using t.equals instead of t.deepequals in here - https://github.com/NodeGroup2/GRAGS/blob/master/tests/tape-tests.js

[tape docs](https://github.com/substack/tape#tdeepequalactual-expected-msg)

**Comment by msachi** [comment]
@sohilpandya As far as we understand it, t.equal is for comparing primitive values, and t.deepequal is for objects / arrays. We only compare numbers and strings...
