### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by RhodesPeter** [NodeGroup2/GRAGS#29]
Get up and running on Heroku. I had a few issues getting it working (lots of issues). If you have tried but are having problems I can help you if you want/need it. Adding Hapi to the mix brings it's own problems.

**Comment by msachi** [comment]
Thanks @RhodesPeter, we could definitely use some help! 😅 Tried playing with dependencies and start commands, but that doesn't seem to be (the only) issue...

**Comment by RhodesPeter** [comment]
This is the process I went through to get ours working: https://github.com/a-la-node/hapi-project/issues/42
