### ISSUE TITLE
Tidy up branches

### ISSUE THREAD

**Issue by Jbarget** [NodeGroup2/GRAGS#35]
Once branches are merged in you want to tidy up after yourself and delete them if you can

![screen shot 2016-11-23 at 16 35 36](https://cloud.githubusercontent.com/assets/11725595/20570289/f86c2a50-b19a-11e6-8dc4-50a0377685a3.png)

**Comment by msachi** [comment]
Done ☺️

**Comment by Jbarget** [comment]
👍  fab
