### ISSUE TITLE
Global variables within file

### ISSUE THREAD

**Issue by oturnermajor** [NodeGroup2/GRAGS#49]
In your server file you have these [global variables](https://github.com/NodeGroup2/GRAGS/blob/master/src/server.js#L8-L13) which are accessed and mutated by the various different route handlers.

What was the rationale for doing things this way rather than creating new variables for each request which would be restricted to the scope of their handlers?

**Comment by stevehopkinson** [comment]
https://github.com/NodeGroup2/GRAGS/issues/45

;-)
