### ISSUE TITLE
Setup simple Hapi server using TDD 

### ISSUE THREAD

**Issue by marisid** [NodeGroup2/GRAGS#5]
- Separate router and handler modules
- Search into the npm `request` module and understand how it works so that we can make API requests
- Agree on endpoints: 
* /recipes + a query parameter for recipe search
* /recipes/ingredients + a query parameter with an array of ingredients to search through the Tesco API

**Comment by marisid** [comment]
Might be a good idea to use `good` and `good-console` modules to print out details of our requests/responses for debugging purposes.

**Comment by msachi** [comment]
Let's change '/recipes/ingredients' to just '/ingredients'

**Comment by marisid** [comment]
Some of the tape tests fail after we implemented requests the Recipe Puppy API. We have to fix them but I don't know how to test a rendered template as a response when using `server.inject`. I spent some time yesterday night but it seemed complicated.

**Comment by marisid** [comment]
All fixed now. Thanks @msachi :+1:
