### ISSUE TITLE
Tesco API data

### ISSUE THREAD

**Issue by marisid** [NodeGroup2/GRAGS#7]
List of ingredients for selected recipe through the Tesco API displaying:
1. Name of the product
2. Image (it comes as 90x90 pixels by default --> change to 540x540 pixels and then scale down to achieve decent resolution)
3. Price
4. Unit price and unit quantity

We need to save all these data in an object (maybe?) so that we can access later for rendering templates.

**Comment by esraajb** [comment]
implemented the first three and didn't have time to implement the forth one.
